[306058] NoClassDefFoundError coming from the TaglibHelper [313181] Java EE import fails if zip entries contain leading slashes [313399] Opener of Archive didn't close a file [313608] random build/compile error due to out of sync files [313630] V1 Validator extension point changes for performance